/**
 * Seed.gs — одноразовая заливка 85 сертификатов в лист `certificates`.
 *
 * КАК ПОЛЬЗОВАТЬСЯ:
 *   1. В редакторе Apps Script → New file → назови "Seed" → тип Script (.gs)
 *   2. Скопируй сюда всё содержимое этого файла
 *   3. Убедись что SHEET_ID в Script Properties уже задан
 *   4. Запусти initSpreadsheet() один раз (если ещё не запускал)
 *   5. Выбери функцию seedCerts() в выпадающем списке сверху → Run
 *   6. В логе должно быть: "Seeded: 85 / 85"
 *   7. После успешной заливки можешь удалить этот файл
 */

/**
 * ИДЕМПОТЕНТНАЯ заливка: НЕ перезаписывает существующие строки.
 * Добавляет только те ID, которых нет в листе. Поэтому твои ручные
 * правки в таблице (часы, имена, email) больше НЕ будут стираться,
 * сколько бы раз эту функцию ни запускали.
 */
function seedCerts() {
  const id = PropertiesService.getScriptProperties().getProperty('SHEET_ID');
  if (!id) throw new Error('SHEET_ID не задан в Script Properties');
  const ss = SpreadsheetApp.openById(id);
  const sh = ss.getSheetByName('certificates');
  if (!sh) throw new Error('Лист certificates не найден. Запусти сначала initSpreadsheet()');

  const headers = sh.getRange(1, 1, 1, sh.getLastColumn()).getValues()[0];
  const idCol = headers.indexOf('id');

  // Существующие ID — чтобы не дублировать и не затирать
  const existingIds = new Set();
  if (sh.getLastRow() > 1) {
    const ids = sh.getRange(2, idCol + 1, sh.getLastRow() - 1, 1).getValues();
    ids.forEach(r => { if (r[0] !== '' && r[0] != null) existingIds.add(String(r[0])); });
  }

  const data = SEED_DATA;
  const now = new Date();
  const newRows = data.filter(r => !existingIds.has(String(r.id)));
  const values = newRows.map(row => headers.map(h => {
    if (h === 'created_at') return now;
    return row[h] !== undefined ? row[h] : '';
  }));

  if (values.length) {
    sh.getRange(sh.getLastRow() + 1, 1, values.length, headers.length).setValues(values);
  }

  Logger.log('Seeded NEW: ' + values.length + ' / kept existing: ' + existingIds.size);
  return values.length;
}

/**
 * ОПАСНО: полная пересборка с нуля. Запускай только если действительно
 * хочешь стереть все правки и вернуть исходные 85 сертификатов.
 */
function seedCertsRESET_DESTRUCTIVE() {
  const id = PropertiesService.getScriptProperties().getProperty('SHEET_ID');
  if (!id) throw new Error('SHEET_ID не задан');
  const sh = SpreadsheetApp.openById(id).getSheetByName('certificates');
  if (sh.getLastRow() > 1) {
    sh.getRange(2, 1, sh.getLastRow() - 1, sh.getLastColumn()).clearContent();
  }
  const headers = sh.getRange(1, 1, 1, sh.getLastColumn()).getValues()[0];
  const now = new Date();
  const values = SEED_DATA.map(row => headers.map(h =>
    h === 'created_at' ? now : (row[h] !== undefined ? row[h] : '')
  ));
  if (values.length) sh.getRange(2, 1, values.length, headers.length).setValues(values);
  Logger.log('FULL RESET: ' + values.length);
  return values.length;
}

const SEED_DATA = [
{
"id": "032513544",
"display_id": "032513544",
"full_name": "Fidan Gasimova",
"first_name": "Fidan",
"last_name": "Gasimova",
"email": "",
"program": "Child Psychology / Cognitive behavioural therapy",
"module": "",
"hours": 72,
"courses_count": 2,
"courses_raw": "Child Psychology (36 hours) | Cognitive behavioural therapy (36 hours)",
"issue_date": "2024-04-03",
"issued_by": "IPAS / IPI",
"status": "valid",
"membership_type": "Community Member",
"valid_period": "03/04/2024 - 05/04/2025",
"language": "in azerbaijani and russian language",
"director": "Society Ambasador Kenan Rahimov",
"teacher": "Tamilla Suleymanova",
"source_url": "https://www.intpas.com/032513544"
},
{
"id": "032513545",
"display_id": "032513545",
"full_name": "Elvin Karimov",
"first_name": "Elvin",
"last_name": "Karimov",
"email": "",
"program": "Child Psychology",
"module": "",
"hours": 36,
"courses_count": 1,
"courses_raw": "Child Psychology (36 hours)",
"issue_date": "2024-04-03",
"issued_by": "IPAS / IPI",
"status": "valid",
"membership_type": "Community Member",
"valid_period": "03/04/2024 - 05/04/2025",
"language": "in azerbaijani and russian language",
"director": "Society Ambasador Kenan Rahimov",
"teacher": "Tamilla Suleymanova",
"source_url": "https://www.intpas.com/032513545"
},
{
"id": "032513546",
"display_id": "032513546",
"full_name": "Sabina Pashazadeh",
"first_name": "Sabina",
"last_name": "Pashazadeh",
"email": "",
"program": "Child Psychology / Cognitive behavioural therapy",
"module": "",
"hours": 72,
"courses_count": 2,
"courses_raw": "Child Psychology (36 hours) | Cognitive behavioural therapy (36 hours)",
"issue_date": "2024-04-03",
"issued_by": "IPAS / IPI",
"status": "valid",
"membership_type": "Community Member",
"valid_period": "03/04/2024 - 05/04/2025",
"language": "in azerbaijani and russian language",
"director": "Society Ambasador Kenan Rahimov",
"teacher": "Tamilla Suleymanova",
"source_url": "https://www.intpas.com/032513546"
},
{
"id": "032513547",
"display_id": "032513547",
"full_name": "Aysun Alyarova",
"first_name": "Aysun",
"last_name": "Alyarova",
"email": "",
"program": "Child Psychology / Cognitive behavioural therapy",
"module": "",
"hours": 72,
"courses_count": 2,
"courses_raw": "Child Psychology (36 hours) | Cognitive behavioural therapy (36 hours)",
"issue_date": "2024-04-03",
"issued_by": "IPAS / IPI",
"status": "valid",
"membership_type": "Community Member",
"valid_period": "03/04/2024 - 05/04/2025",
"language": "in azerbaijani and russian language",
"director": "Society Ambasador Kenan Rahimov",
"teacher": "Tamilla Suleymanova",
"source_url": "https://www.intpas.com/032513547"
},
{
"id": "032513548",
"display_id": "032513548",
"full_name": "Aytan Huseynova",
"first_name": "Aytan",
"last_name": "Huseynova",
"email": "",
"program": "Child Psychology / Cognitive behavioural therapy",
"module": "",
"hours": 72,
"courses_count": 2,
"courses_raw": "Child Psychology (36 hours) | Cognitive behavioural therapy (36 hours)",
"issue_date": "2024-04-03",
"issued_by": "IPAS / IPI",
"status": "valid",
"membership_type": "Community Member",
"valid_period": "03/04/2024 - 05/04/2025",
"language": "in azerbaijani and russian language",
"director": "Society Ambasador Kenan Rahimov",
"teacher": "Tamilla Suleymanova",
"source_url": "https://www.intpas.com/032513548"
},
{
"id": "032513549",
"display_id": "032513549",
"full_name": "Bahar Rzayeva",
"first_name": "Bahar",
"last_name": "Rzayeva",
"email": "",
"program": "Clinical Child and Adolescent Psychology / Applied Behavior Analysis (ABA) Therapy",
"module": "",
"hours": 84,
"courses_count": 2,
"courses_raw": "Clinical Child and Adolescent Psychology (42 hours) | Applied Behavior Analysis (ABA) Therapy (42 hours)",
"issue_date": "2024-04-03",
"issued_by": "IPAS / IPI",
"status": "valid",
"membership_type": "Community Member",
"valid_period": "03/04/2024 - 05/04/2025",
"language": "in azerbaijani language",
"director": "",
"teacher": "Society Ambasador Kenan Rahimov",
"source_url": "https://www.intpas.com/032513549"
},
{
"id": "032513550",
"display_id": "032513550",
"full_name": "Samira Rustamova",
"first_name": "Samira",
"last_name": "Rustamova",
"email": "",
"program": "Clinical Psychology and Psychotherapy / Clinical Child and Adolescent Psychology / Couples Counselling in Family Therapy",
"module": "",
"hours": 284,
"courses_count": 3,
"courses_raw": "Clinical Psychology and Psychotherapy (200 hours) | Clinical Child and Adolescent Psychology (42 hours) | Couples Counselling in Family Therapy (42 hours)",
"issue_date": "2022-04-03",
"issued_by": "IPAS / IPI",
"status": "valid",
"membership_type": "Community Member",
"valid_period": "03/04/2022 - 05/04/2025",
"language": "in azerbaijani language",
"director": "",
"teacher": "Society Ambasador Kenan Rahimov",
"source_url": "https://www.intpas.com/032513550"
},
{
"id": "032513552",
"display_id": "032513552",
"full_name": "Gulchin Aliyeva",
"first_name": "Gulchin",
"last_name": "Aliyeva",
"email": "",
"program": "Couples Counselling in Family Therapy",
"module": "",
"hours": 36,
"courses_count": 1,
"courses_raw": "Couples Counselling in Family Therapy (36 hours)",
"issue_date": "2024-05-20",
"issued_by": "IPAS / IPI",
"status": "valid",
"membership_type": "Community Member",
"valid_period": "20/05/2024 - 20/05/2025",
"language": "in azerbaijani language",
"director": "Society Ambasador Kenan Rahimov",
"teacher": "Samira Rustamova",
"source_url": "https://www.intpas.com/032513552"
},
{
"id": "032513553",
"display_id": "032513553",
"full_name": "Gullu Huseynova",
"first_name": "Gullu",
"last_name": "Huseynova",
"email": "",
"program": "Clinical&nbsp; Psychotherapy / Couples Counselling in Family Therapy",
"module": "",
"hours": 236,
"courses_count": 2,
"courses_raw": "Clinical&nbsp; Psychotherapy (200 hours) | Couples Counselling in Family Therapy (36 hours)",
"issue_date": "2024-05-20",
"issued_by": "IPAS / IPI",
"status": "valid",
"membership_type": "Community Member",
"valid_period": "20/05/2024 - 20/05/2025",
"language": "in azerbaijani language",
"director": "Society Ambasador Kenan Rahimov",
"teacher": "Kenan Rahimov",
"source_url": "https://www.intpas.com/032513553"
},
{
"id": "032513554",
"display_id": "032513554",
"full_name": "Lala Mammadova",
"first_name": "Lala",
"last_name": "Mammadova",
"email": "",
"program": "Couples Counselling in Family Therapy",
"module": "",
"hours": 36,
"courses_count": 1,
"courses_raw": "Couples Counselling in Family Therapy (36 hours)",
"issue_date": "2024-05-20",
"issued_by": "IPAS / IPI",
"status": "valid",
"membership_type": "Community Member",
"valid_period": "20/05/2024 - 20/05/2025",
"language": "in azerbaijani language",
"director": "Society Ambasador Kenan Rahimov",
"teacher": "Samira Rustamova",
"source_url": "https://www.intpas.com/032513554"
},
{
"id": "032513555",
"display_id": "032513555",
"full_name": "Lala Kahramanova",
"first_name": "Lala",
"last_name": "Kahramanova",
"email": "",
"program": "Couples Counselling in Family Therapy",
"module": "",
"hours": 36,
"courses_count": 1,
"courses_raw": "Couples Counselling in Family Therapy (36 hours)",
"issue_date": "2024-05-20",
"issued_by": "IPAS / IPI",
"status": "valid",
"membership_type": "Community Member",
"valid_period": "20/05/2024 - 20/05/2025",
"language": "in azerbaijani language",
"director": "Society Ambasador Kenan Rahimov",
"teacher": "Samira Rustamova",
"source_url": "https://www.intpas.com/032513555"
},
{
"id": "032513556",
"display_id": "032513556",
"full_name": "Khayala Khasmammadli",
"first_name": "Khayala",
"last_name": "Khasmammadli",
"email": "",
"program": "Couples Counselling in Family Therapy",
"module": "",
"hours": 36,
"courses_count": 1,
"courses_raw": "Couples Counselling in Family Therapy (36 hours)",
"issue_date": "2024-05-20",
"issued_by": "IPAS / IPI",
"status": "valid",
"membership_type": "Community Member",
"valid_period": "20/05/2024 - 20/05/2025",
"language": "in azerbaijani language",
"director": "Society Ambasador Kenan Rahimov",
"teacher": "Samira Rustamova",
"source_url": "https://www.intpas.com/032513556"
},
{
"id": "032513557",
"display_id": "032513557",
"full_name": "Sadagat Huseynova",
"first_name": "Sadagat",
"last_name": "Huseynova",
"email": "",
"program": "Couples Counselling in Family Therapy",
"module": "",
"hours": 36,
"courses_count": 1,
"courses_raw": "Couples Counselling in Family Therapy (36 hours)",
"issue_date": "2024-05-20",
"issued_by": "IPAS / IPI",
"status": "valid",
"membership_type": "Community Member",
"valid_period": "20/05/2024 - 20/05/2025",
"language": "in azerbaijani language",
"director": "Society Ambasador Kenan Rahimov",
"teacher": "Samira Rustamova",
"source_url": "https://www.intpas.com/032513557"
},
{
"id": "032513558",
"display_id": "032513558",
"full_name": "Sevinj Akkurt",
"first_name": "Sevinj",
"last_name": "Akkurt",
"email": "",
"program": "Couples Counselling in Family Therapy",
"module": "",
"hours": 36,
"courses_count": 1,
"courses_raw": "Couples Counselling in Family Therapy (36 hours)",
"issue_date": "2024-05-20",
"issued_by": "IPAS / IPI",
"status": "valid",
"membership_type": "Community Member",
"valid_period": "20/05/2024 - 20/05/2025",
"language": "in azerbaijani language",
"director": "Society Ambasador Kenan Rahimov",
"teacher": "Samira Rustamova",
"source_url": "https://www.intpas.com/032513558"
},
{
"id": "032513559",
"display_id": "032513559",
"full_name": "Sevda Kerimova",
"first_name": "Sevda",
"last_name": "Kerimova",
"email": "",
"program": "Clinical Psychotherapy",
"module": "",
"hours": 200,
"courses_count": 1,
"courses_raw": "Clinical Psychotherapy (200 hours)",
"issue_date": "2024-05-20",
"issued_by": "IPAS / IPI",
"status": "valid",
"membership_type": "Community Member",
"valid_period": "20/05/2024 - 20/05/2025",
"language": "in azerbaijani language",
"director": "Society Ambasador Kenan Rahimov",
"teacher": "Samira Rustamova",
"source_url": "https://www.intpas.com/032513559"
},
{
"id": "032513560",
"display_id": "032513560",
"full_name": "Nazakat Mirzazada",
"first_name": "Nazakat",
"last_name": "Mirzazada",
"email": "",
"program": "Clinical Psychotherapy",
"module": "",
"hours": 200,
"courses_count": 1,
"courses_raw": "Clinical Psychotherapy (200 hours)",
"issue_date": "2024-05-20",
"issued_by": "IPAS / IPI",
"status": "valid",
"membership_type": "Community Member",
"valid_period": "20/05/2024 - 20/05/2025",
"language": "in azerbaijani language",
"director": "Society Ambasador Kenan Rahimov",
"teacher": "Kenan Rahimov",
"source_url": "https://www.intpas.com/032513560"
},
{
"id": "032513561",
"display_id": "032513561",
"full_name": "Ramila Agayeva",
"first_name": "Ramila",
"last_name": "Agayeva",
"email": "",
"program": "Clinical Psychotherapy",
"module": "",
"hours": 200,
"courses_count": 1,
"courses_raw": "Clinical Psychotherapy (200 hours)",
"issue_date": "2024-05-20",
"issued_by": "IPAS / IPI",
"status": "valid",
"membership_type": "Community Member",
"valid_period": "20/05/2024 - 20/05/2025",
"language": "in russian language",
"director": "Society Ambasador Kenan Rahimov",
"teacher": "Kenan Rahimov",
"source_url": "https://www.intpas.com/032513561"
},
{
"id": "032513562",
"display_id": "032513562",
"full_name": "Zehra Zahidova",
"first_name": "Zehra",
"last_name": "Zahidova",
"email": "",
"program": "Clinical Psychotherapy",
"module": "",
"hours": 200,
"courses_count": 1,
"courses_raw": "Clinical Psychotherapy (200 hours)",
"issue_date": "2024-05-20",
"issued_by": "IPAS / IPI",
"status": "valid",
"membership_type": "Community Member",
"valid_period": "20/05/2024 - 20/05/2025",
"language": "in azerbaijani language",
"director": "Society Ambasador Kenan Rahimov",
"teacher": "Kenan Rahimov",
"source_url": "https://www.intpas.com/032513562"
},
{
"id": "032513563",
"display_id": "032513563",
"full_name": "Zeynab Rzayeva",
"first_name": "Zeynab",
"last_name": "Rzayeva",
"email": "",
"program": "Clinical Psychotherapy",
"module": "",
"hours": 200,
"courses_count": 1,
"courses_raw": "Clinical Psychotherapy (200 hours)",
"issue_date": "2024-05-20",
"issued_by": "IPAS / IPI",
"status": "valid",
"membership_type": "Community Member",
"valid_period": "20/05/2024 - 20/05/2025",
"language": "in azerbaijani language",
"director": "Society Ambasador Kenan Rahimov",
"teacher": "Kenan Rahimov",
"source_url": "https://www.intpas.com/032513563"
},
{
"id": "032513564",
"display_id": "032513564",
"full_name": "Vitaliy Vaytenko",
"first_name": "Vitaliy",
"last_name": "Vaytenko",
"email": "",
"program": "Clinical Psychotherapy",
"module": "",
"hours": 200,
"courses_count": 1,
"courses_raw": "Clinical Psychotherapy (200 hours)",
"issue_date": "2024-05-20",
"issued_by": "IPAS / IPI",
"status": "valid",
"membership_type": "Community Member",
"valid_period": "20/05/2024 - 20/05/2025",
"language": "in russian language",
"director": "Society Ambasador Kenan Rahimov",
"teacher": "Kenan Rahimov",
"source_url": "https://www.intpas.com/032513564"
},
{
"id": "032513565",
"display_id": "032513565",
"full_name": "Zehra Farzaliyeva",
"first_name": "Zehra",
"last_name": "Farzaliyeva",
"email": "",
"program": "Clinical Psychotherapy",
"module": "",
"hours": 200,
"courses_count": 1,
"courses_raw": "Clinical Psychotherapy (200 hours)",
"issue_date": "2024-05-20",
"issued_by": "IPAS / IPI",
"status": "valid",
"membership_type": "Community Member",
"valid_period": "20/05/2024 - 20/05/2025",
"language": "in azerbaijani language",
"director": "Society Ambasador Kenan Rahimov",
"teacher": "Kenan Rahimov",
"source_url": "https://www.intpas.com/032513565"
},
{
"id": "032513566",
"display_id": "032513566",
"full_name": "Aytaj Aghadadayeva",
"first_name": "Aytaj",
"last_name": "Aghadadayeva",
"email": "",
"program": "Clinical Psychotherapy",
"module": "",
"hours": 200,
"courses_count": 1,
"courses_raw": "Clinical Psychotherapy (200 hours)",
"issue_date": "2024-05-20",
"issued_by": "IPAS / IPI",
"status": "valid",
"membership_type": "Community Member",
"valid_period": "20/05/2024 - 20/05/2025",
"language": "in azerbaijani language",
"director": "Society Ambasador Kenan Rahimov",
"teacher": "Kenan Rahimov",
"source_url": "https://www.intpas.com/032513566"
},
{
"id": "032513567",
"display_id": "032513567",
"full_name": "Vusala Alizadeh",
"first_name": "Vusala",
"last_name": "Alizadeh",
"email": "",
"program": "Clinical Psychotherapy",
"module": "",
"hours": 200,
"courses_count": 1,
"courses_raw": "Clinical Psychotherapy (200 hours)",
"issue_date": "2024-05-20",
"issued_by": "IPAS / IPI",
"status": "valid",
"membership_type": "Community Member",
"valid_period": "20/05/2024 - 20/05/2025",
"language": "in azerbaijani language",
"director": "Society Ambasador Kenan Rahimov",
"teacher": "Kenan Rahimov",
"source_url": "https://www.intpas.com/032513567"
},
{
"id": "032513568",
"display_id": "032513568",
"full_name": "Vusala Amirova",
"first_name": "Vusala",
"last_name": "Amirova",
"email": "",
"program": "Clinical Psychotherapy",
"module": "",
"hours": 200,
"courses_count": 1,
"courses_raw": "Clinical Psychotherapy (200 hours)",
"issue_date": "2024-05-20",
"issued_by": "IPAS / IPI",
"status": "valid",
"membership_type": "Community Member",
"valid_period": "20/05/2024 - 20/05/2025",
"language": "in azerbaijani language",
"director": "Society Ambasador Kenan Rahimov",
"teacher": "Kenan Rahimov",
"source_url": "https://www.intpas.com/032513568"
},
{
"id": "032513569",
"display_id": "032513569",
"full_name": "Aytekin Imanova",
"first_name": "Aytekin",
"last_name": "Imanova",
"email": "",
"program": "Clinical Psychotherapy",
"module": "",
"hours": 200,
"courses_count": 1,
"courses_raw": "Clinical Psychotherapy (200 hours)",
"issue_date": "2024-05-20",
"issued_by": "IPAS / IPI",
"status": "valid",
"membership_type": "Community Member",
"valid_period": "20/05/2024 - 20/05/2025",
"language": "in azerbaijani language",
"director": "Society Ambasador Kenan Rahimov",
"teacher": "Kenan Rahimov",
"source_url": "https://www.intpas.com/032513569"
},
{
"id": "032513570",
"display_id": "032513570",
"full_name": "Aziza Quliyeva",
"first_name": "Aziza",
"last_name": "Quliyeva",
"email": "",
"program": "Clinical Psychotherapy",
"module": "",
"hours": 200,
"courses_count": 1,
"courses_raw": "Clinical Psychotherapy (200 hours)",
"issue_date": "2024-05-20",
"issued_by": "IPAS / IPI",
"status": "valid",
"membership_type": "Community Member",
"valid_period": "20/05/2024 - 20/05/2025",
"language": "in azerbaijani language",
"director": "Society Ambasador Kenan Rahimov",
"teacher": "Kenan Rahimov",
"source_url": "https://www.intpas.com/032513570"
},
{
"id": "032513571",
"display_id": "032513571",
"full_name": "Gunel Akbarova",
"first_name": "Gunel",
"last_name": "Akbarova",
"email": "",
"program": "Clinical Psychotherapy",
"module": "",
"hours": 200,
"courses_count": 1,
"courses_raw": "Clinical Psychotherapy (200 hours)",
"issue_date": "2024-05-20",
"issued_by": "IPAS / IPI",
"status": "valid",
"membership_type": "Community Member",
"valid_period": "20/05/2024 - 20/05/2025",
"language": "in azerbaijani language",
"director": "Society Ambasador Kenan Rahimov",
"teacher": "Kenan Rahimov",
"source_url": "https://www.intpas.com/032513571"
},
{
"id": "032513572",
"display_id": "032513572",
"full_name": "Sabina Alakperova",
"first_name": "Sabina",
"last_name": "Alakperova",
"email": "",
"program": "Clinical Psychotherapy",
"module": "",
"hours": 200,
"courses_count": 1,
"courses_raw": "Clinical Psychotherapy (200 hours)",
"issue_date": "2024-05-20",
"issued_by": "IPAS / IPI",
"status": "valid",
"membership_type": "Community Member",
"valid_period": "20/05/2024 - 20/05/2025",
"language": "in azerbaijani language",
"director": "Society Ambasador Kenan Rahimov",
"teacher": "Kenan Rahimov",
"source_url": "https://www.intpas.com/032513572"
},
{
"id": "032513573",
"display_id": "032513573",
"full_name": "Khayala Badalova",
"first_name": "Khayala",
"last_name": "Badalova",
"email": "",
"program": "Clinical Psychotherapy",
"module": "",
"hours": 200,
"courses_count": 1,
"courses_raw": "Clinical Psychotherapy (200 hours)",
"issue_date": "2024-05-20",
"issued_by": "IPAS / IPI",
"status": "valid",
"membership_type": "Community Member",
"valid_period": "20/05/2024 - 20/05/2025",
"language": "in azerbaijani language",
"director": "Society Ambasador Kenan Rahimov",
"teacher": "Kenan Rahimov",
"source_url": "https://www.intpas.com/032513573"
},
{
"id": "032513574",
"display_id": "032513574",
"full_name": "Ayshan Gasimova",
"first_name": "Ayshan",
"last_name": "Gasimova",
"email": "",
"program": "Clinical Psychotherapy",
"module": "",
"hours": 200,
"courses_count": 1,
"courses_raw": "Clinical Psychotherapy (200 hours)",
"issue_date": "2024-05-20",
"issued_by": "IPAS / IPI",
"status": "valid",
"membership_type": "Community Member",
"valid_period": "20/05/2024 - 20/05/2025",
"language": "in azerbaijani language",
"director": "Society Ambasador Kenan Rahimov",
"teacher": "Kenan Rahimov",
"source_url": "https://www.intpas.com/032513574"
},
{
"id": "032513575",
"display_id": "032513575",
"full_name": "Gunay Huseynova",
"first_name": "Gunay",
"last_name": "Huseynova",
"email": "",
"program": "Clinical Psychotherapy",
"module": "",
"hours": 200,
"courses_count": 1,
"courses_raw": "Clinical Psychotherapy (200 hours)",
"issue_date": "2024-05-20",
"issued_by": "IPAS / IPI",
"status": "valid",
"membership_type": "Community Member",
"valid_period": "20/05/2024 - 20/05/2025",
"language": "in azerbaijani language",
"director": "Society Ambasador Kenan Rahimov",
"teacher": "Kenan Rahimov",
"source_url": "https://www.intpas.com/032513575"
},
{
"id": "032513576",
"display_id": "032513576",
"full_name": "Leyla Ahmadova",
"first_name": "Leyla",
"last_name": "Ahmadova",
"email": "",
"program": "Clinical Psychotherapy",
"module": "",
"hours": 200,
"courses_count": 1,
"courses_raw": "Clinical Psychotherapy (200 hours)",
"issue_date": "2024-05-20",
"issued_by": "IPAS / IPI",
"status": "valid",
"membership_type": "Community Member",
"valid_period": "20/05/2024 - 20/05/2025",
"language": "in azerbaijani language",
"director": "Society Ambasador Kenan Rahimov",
"teacher": "Kenan Rahimov",
"source_url": "https://www.intpas.com/032513576"
},
{
"id": "032513577",
"display_id": "032513577",
"full_name": "Gulnar Samedova",
"first_name": "Gulnar",
"last_name": "Samedova",
"email": "",
"program": "Clinical Psychotherapy",
"module": "",
"hours": 200,
"courses_count": 1,
"courses_raw": "Clinical Psychotherapy (200 hours)",
"issue_date": "2024-05-20",
"issued_by": "IPAS / IPI",
"status": "valid",
"membership_type": "Community Member",
"valid_period": "20/05/2024 - 20/05/2025",
"language": "in azerbaijani language",
"director": "Society Ambasador Kenan Rahimov",
"teacher": "Kenan Rahimov",
"source_url": "https://www.intpas.com/032513577"
},
{
"id": "032513578",
"display_id": "032513578",
"full_name": "Afsana Jafarova",
"first_name": "Afsana",
"last_name": "Jafarova",
"email": "",
"program": "Clinical Psychotherapy",
"module": "",
"hours": 200,
"courses_count": 1,
"courses_raw": "Clinical Psychotherapy (200 hours)",
"issue_date": "2024-05-20",
"issued_by": "IPAS / IPI",
"status": "valid",
"membership_type": "Community Member",
"valid_period": "20/05/2024 - 20/05/2025",
"language": "in azerbaijani language",
"director": "Society Ambasador Kenan Rahimov",
"teacher": "Kenan Rahimov",
"source_url": "https://www.intpas.com/032513578"
},
{
"id": "032513579",
"display_id": "032513579",
"full_name": "Natalya Sleptsova",
"first_name": "Natalya",
"last_name": "Sleptsova",
"email": "",
"program": "Clinical Psychotherapy",
"module": "",
"hours": 200,
"courses_count": 1,
"courses_raw": "Clinical Psychotherapy (200 hours)",
"issue_date": "2024-05-20",
"issued_by": "IPAS / IPI",
"status": "valid",
"membership_type": "Community Member",
"valid_period": "20/05/2024 - 20/05/2025",
"language": "in russian language",
"director": "Society Ambasador Kenan Rahimov",
"teacher": "Kenan Rahimov",
"source_url": "https://www.intpas.com/032513579"
},
{
"id": "032513580",
"display_id": "032513580",
"full_name": "Aysel Mustafayeva",
"first_name": "Aysel",
"last_name": "Mustafayeva",
"email": "",
"program": "Clinical Psychotherapy",
"module": "",
"hours": 200,
"courses_count": 1,
"courses_raw": "Clinical Psychotherapy (200 hours)",
"issue_date": "2024-05-20",
"issued_by": "IPAS / IPI",
"status": "valid",
"membership_type": "Community Member",
"valid_period": "20/05/2024 - 20/05/2025",
"language": "in azerbaijani language",
"director": "Society Ambasador Kenan Rahimov",
"teacher": "Kenan Rahimov",
"source_url": "https://www.intpas.com/032513580"
},
{
"id": "032513581",
"display_id": "032513581",
"full_name": "Alvina Huseyinova",
"first_name": "Alvina",
"last_name": "Huseyinova",
"email": "",
"program": "Couples Counselling in Family Therapy",
"module": "",
"hours": 32,
"courses_count": 1,
"courses_raw": "Couples Counselling in Family Therapy (32 hours)",
"issue_date": "2024-10-05",
"issued_by": "IPAS / IPI",
"status": "valid",
"membership_type": "Community Member",
"valid_period": "05/10/2024 - 05/10/2025",
"language": "in azerbaijani language",
"director": "Society Ambasador Kenan Rahimov",
"teacher": "Samira Rustamova",
"source_url": "https://www.intpas.com/032513581"
},
{
"id": "032513582",
"display_id": "032513582",
"full_name": "Sevich Abbaszada",
"first_name": "Sevich",
"last_name": "Abbaszada",
"email": "",
"program": "Basic Psychotherapy",
"module": "",
"hours": 48,
"courses_count": 1,
"courses_raw": "Basic Psychotherapy (48 hours)",
"issue_date": "2024-07-09",
"issued_by": "IPAS / IPI",
"status": "valid",
"membership_type": "Community Member",
"valid_period": "09/07/2024 - 09/07/2025",
"language": "in azerbaijani language",
"director": "Society Ambasador Kenan Rahimov",
"teacher": "Aysel Mehdiyeva",
"source_url": "https://www.intpas.com/032513582"
},
{
"id": "032513583",
"display_id": "032513583",
"full_name": "Elza Shukurova",
"first_name": "Elza",
"last_name": "Shukurova",
"email": "",
"program": "Couples Counselling in Family Therapy",
"module": "",
"hours": 32,
"courses_count": 1,
"courses_raw": "Couples Counselling in Family Therapy (32 hours)",
"issue_date": "2024-10-05",
"issued_by": "IPAS / IPI",
"status": "valid",
"membership_type": "Community Member",
"valid_period": "05/10/2024 - 05/10/2025",
"language": "in azerbaijani language",
"director": "Society Ambasador Kenan Rahimov",
"teacher": "Samira Rustamova",
"source_url": "https://www.intpas.com/032513583"
},
{
"id": "032513584",
"display_id": "032513584",
"full_name": "Kamala Aliyeva",
"first_name": "Kamala",
"last_name": "Aliyeva",
"email": "",
"program": "Couples Counselling in Family Therapy",
"module": "",
"hours": 32,
"courses_count": 1,
"courses_raw": "Couples Counselling in Family Therapy (32 hours)",
"issue_date": "2024-10-05",
"issued_by": "IPAS / IPI",
"status": "valid",
"membership_type": "Community Member",
"valid_period": "05/10/2024 - 05/10/2025",
"language": "in azerbaijani language",
"director": "Society Ambasador Kenan Rahimov",
"teacher": "Samira Rustamova",
"source_url": "https://www.intpas.com/032513584"
},
{
"id": "032513585",
"display_id": "032513585",
"full_name": "Konul Salimova",
"first_name": "Konul",
"last_name": "Salimova",
"email": "",
"program": "Couples Counselling in Family Therapy",
"module": "",
"hours": 32,
"courses_count": 1,
"courses_raw": "Couples Counselling in Family Therapy (32 hours)",
"issue_date": "2024-10-05",
"issued_by": "IPAS / IPI",
"status": "valid",
"membership_type": "Community Member",
"valid_period": "05/10/2024 - 05/10/2025",
"language": "in azerbaijani language",
"director": "Society Ambasador Kenan Rahimov",
"teacher": "Samira Rustamova",
"source_url": "https://www.intpas.com/032513585"
},
{
"id": "032513586",
"display_id": "032513586",
"full_name": "Husniya Nasirova",
"first_name": "Husniya",
"last_name": "Nasirova",
"email": "",
"program": "Couples Counselling in Family Therapy",
"module": "",
"hours": 32,
"courses_count": 1,
"courses_raw": "Couples Counselling in Family Therapy (32 hours)",
"issue_date": "2024-10-05",
"issued_by": "IPAS / IPI",
"status": "valid",
"membership_type": "Community Member",
"valid_period": "05/10/2024 - 05/10/2025",
"language": "in azerbaijani language",
"director": "Society Ambasador Kenan Rahimov",
"teacher": "Samira Rustamova",
"source_url": "https://www.intpas.com/032513586"
},
{
"id": "032513587",
"display_id": "032513587",
"full_name": "Rena Javadzade",
"first_name": "Rena",
"last_name": "Javadzade",
"email": "",
"program": "Couples Counselling in Family Therapy",
"module": "",
"hours": 32,
"courses_count": 1,
"courses_raw": "Couples Counselling in Family Therapy (32 hours)",
"issue_date": "2024-10-05",
"issued_by": "IPAS / IPI",
"status": "valid",
"membership_type": "Community Member",
"valid_period": "05/10/2024 - 05/10/2025",
"language": "in azerbaijani language",
"director": "Society Ambasador Kenan Rahimov",
"teacher": "Samira Rustamova",
"source_url": "https://www.intpas.com/032513587"
},
{
"id": "032513588",
"display_id": "032513588",
"full_name": "Sevil Hajiyeva",
"first_name": "Sevil",
"last_name": "Hajiyeva",
"email": "",
"program": "Couples Counselling in Family Therapy",
"module": "",
"hours": 32,
"courses_count": 1,
"courses_raw": "Couples Counselling in Family Therapy (32 hours)",
"issue_date": "2024-10-05",
"issued_by": "IPAS / IPI",
"status": "valid",
"membership_type": "Community Member",
"valid_period": "05/10/2024 - 05/10/2025",
"language": "in azerbaijani language",
"director": "Society Ambasador Kenan Rahimov",
"teacher": "Samira Rustamova",
"source_url": "https://www.intpas.com/032513588"
},
{
"id": "032513589",
"display_id": "032513589",
"full_name": "Shafag Gurbanova",
"first_name": "Shafag",
"last_name": "Gurbanova",
"email": "",
"program": "Couples Counselling in Family Therapy",
"module": "",
"hours": 32,
"courses_count": 1,
"courses_raw": "Couples Counselling in Family Therapy (32 hours)",
"issue_date": "2024-10-05",
"issued_by": "IPAS / IPI",
"status": "valid",
"membership_type": "Community Member",
"valid_period": "05/10/2024 - 05/10/2025",
"language": "in azerbaijani language",
"director": "Society Ambasador Kenan Rahimov",
"teacher": "Samira Rustamova",
"source_url": "https://www.intpas.com/032513589"
},
{
"id": "032513590",
"display_id": "032513590",
"full_name": "Aynur Karimova",
"first_name": "Aynur",
"last_name": "Karimova",
"email": "",
"program": "Couples Counselling in Family Therapy",
"module": "",
"hours": 32,
"courses_count": 1,
"courses_raw": "Couples Counselling in Family Therapy (32 hours)",
"issue_date": "2024-10-05",
"issued_by": "IPAS / IPI",
"status": "valid",
"membership_type": "Community Member",
"valid_period": "05/10/2024 - 05/10/2025",
"language": "in azerbaijani language",
"director": "Society Ambasador Kenan Rahimov",
"teacher": "Samira Rustamova",
"source_url": "https://www.intpas.com/032513590"
},
{
"id": "032513615",
"display_id": "032513615",
"full_name": "Shola Shakili",
"first_name": "Shola",
"last_name": "Shakili",
"email": "",
"program": "Clinical Psychotherapy",
"module": "",
"hours": 200,
"courses_count": 2,
"courses_raw": "Clinical Psychotherapy | (200 hours)",
"issue_date": "2025-01-21",
"issued_by": "IPAS / IPI",
"status": "valid",
"membership_type": "Community Member",
"valid_period": "21/01/2025 - 15/01/2026",
"language": "in azerbaijani language",
"director": "Society Ambasador Kenan Rahimov",
"teacher": "Kenan Rahimov",
"source_url": "https://www.intpas.com/032513615"
},
{
"id": "032523120",
"display_id": "032523120",
"full_name": "Maria Davidova",
"first_name": "Maria",
"last_name": "Davidova",
"email": "",
"program": "Child Psychology",
"module": "",
"hours": 36,
"courses_count": 1,
"courses_raw": "Child Psychology (36 hours)",
"issue_date": "2024-07-21",
"issued_by": "IPAS / IPI",
"status": "valid",
"membership_type": "Community Member",
"valid_period": "21/07/2024 - 22/07/2025",
"language": "in azerbaijani and russian language",
"director": "Society Ambasador Kenan Rahimov",
"teacher": "Tamilla Suleymanova",
"source_url": "https://www.intpas.com/032523120"
},
{
"id": "032523121",
"display_id": "032523121",
"full_name": "Khanim Mammadova",
"first_name": "Khanim",
"last_name": "Mammadova",
"email": "",
"program": "Child Psychology",
"module": "",
"hours": 36,
"courses_count": 1,
"courses_raw": "Child Psychology (36 hours)",
"issue_date": "2024-07-21",
"issued_by": "IPAS / IPI",
"status": "valid",
"membership_type": "Community Member",
"valid_period": "21/07/2024 - 22/07/2025",
"language": "in azerbaijani and russian language",
"director": "Society Ambasador Kenan Rahimov",
"teacher": "Tamilla Suleymanova",
"source_url": "https://www.intpas.com/032523121"
},
{
"id": "032523122",
"display_id": "032523122",
"full_name": "Fatima Dadashsoy",
"first_name": "Fatima",
"last_name": "Dadashsoy",
"email": "",
"program": "Child Psychology",
"module": "",
"hours": 36,
"courses_count": 1,
"courses_raw": "Child Psychology (36 hours)",
"issue_date": "2024-07-21",
"issued_by": "IPAS / IPI",
"status": "valid",
"membership_type": "Community Member",
"valid_period": "21/07/2024 - 22/07/2025",
"language": "in azerbaijani and russian language",
"director": "Society Ambasador Kenan Rahimov",
"teacher": "Tamilla Suleymanova",
"source_url": "https://www.intpas.com/032523122"
},
{
"id": "10133501",
"display_id": "032513551",
"full_name": "Esmira Alizadeh",
"first_name": "Esmira",
"last_name": "Alizadeh",
"email": "",
"program": "Couples Counselling in Family Therapy",
"module": "",
"hours": 36,
"courses_count": 1,
"courses_raw": "Couples Counselling in Family Therapy (36 hours)",
"issue_date": "2024-05-20",
"issued_by": "IPAS / IPI",
"status": "valid",
"membership_type": "Community Member",
"valid_period": "20/05/2024 - 20/05/2025",
"language": "in azerbaijani language",
"director": "Society Ambasador Kenan Rahimov",
"teacher": "Samira Rustamova",
"source_url": "https://www.intpas.com/10133501"
},
{
"id": "13iu21e3az001",
"display_id": "13iu21e3az001",
"full_name": "Kenan Rahimov",
"first_name": "Kenan",
"last_name": "Rahimov",
"email": "",
"program": "Clinical Psychotherapy course",
"module": "",
"hours": 0,
"courses_count": 1,
"courses_raw": "Clinical Psychotherapy course",
"issue_date": "2001-09-10",
"issued_by": "IPAS / IPI",
"status": "valid",
"membership_type": "",
"valid_period": "10/09/2001 - 09/09/2003",
"language": "in russian and azerbaijani language",
"director": "Society Ambasador",
"teacher": "",
"source_url": "https://www.intpas.com/13iu21e3az001"
},
{
"id": "13iu21e3az0011",
"display_id": "C032513511",
"full_name": "Adila Abbasova",
"first_name": "Adila",
"last_name": "Abbasova",
"email": "",
"program": "Clinical Psychotherapy course",
"module": "",
"hours": 0,
"courses_count": 1,
"courses_raw": "Clinical Psychotherapy course",
"issue_date": "2023-06-01",
"issued_by": "IPAS / IPI",
"status": "valid",
"membership_type": "Community Member",
"valid_period": "01/06/2023 - 01/06/2024",
"language": "in azerbaijani language",
"director": "Society Ambasador Kenan Rahimov",
"teacher": "",
"source_url": "https://www.intpas.com/13iu21e3az0011"
},
{
"id": "13iu21e3az0012",
"display_id": "C032513512",
"full_name": "Aybeniz Zakiyeva",
"first_name": "Aybeniz",
"last_name": "Zakiyeva",
"email": "",
"program": "Clinical Psychotherapy course",
"module": "",
"hours": 0,
"courses_count": 1,
"courses_raw": "Clinical Psychotherapy course",
"issue_date": "2023-06-01",
"issued_by": "IPAS / IPI",
"status": "valid",
"membership_type": "Community Member",
"valid_period": "01/06/2023 - 01/06/2024",
"language": "in azerbaijani language",
"director": "Society Ambasador Kenan Rahimov",
"teacher": "",
"source_url": "https://www.intpas.com/13iu21e3az0012"
},
{
"id": "13iu21e3az0013",
"display_id": "C032513513",
"full_name": "Aynura Kerimova",
"first_name": "Aynura",
"last_name": "Kerimova",
"email": "",
"program": "Clinical Psychotherapy course",
"module": "",
"hours": 0,
"courses_count": 1,
"courses_raw": "Clinical Psychotherapy course",
"issue_date": "2023-06-01",
"issued_by": "IPAS / IPI",
"status": "valid",
"membership_type": "Community Member",
"valid_period": "01/06/2023 - 01/06/2024",
"language": "in azerbaijani language",
"director": "Society Ambasador Kenan Rahimov",
"teacher": "",
"source_url": "https://www.intpas.com/13iu21e3az0013"
},
{
"id": "13iu21e3az0014",
"display_id": "C032513514",
"full_name": "Aysel Mehdiyeva",
"first_name": "Aysel",
"last_name": "Mehdiyeva",
"email": "",
"program": "Clinical Psychotherapy course",
"module": "",
"hours": 0,
"courses_count": 1,
"courses_raw": "Clinical Psychotherapy course",
"issue_date": "2023-06-01",
"issued_by": "IPAS / IPI",
"status": "valid",
"membership_type": "Community Member",
"valid_period": "01/06/2023 - 01/06/2024",
"language": "in azerbaijani language",
"director": "Society Ambasador Kenan Rahimov",
"teacher": "",
"source_url": "https://www.intpas.com/13iu21e3az0014"
},
{
"id": "13iu21e3az0015",
"display_id": "C032513515",
"full_name": "Ayten Shukurova",
"first_name": "Ayten",
"last_name": "Shukurova",
"email": "",
"program": "Clinical Psychotherapy course",
"module": "",
"hours": 0,
"courses_count": 1,
"courses_raw": "Clinical Psychotherapy course",
"issue_date": "2023-06-01",
"issued_by": "IPAS / IPI",
"status": "valid",
"membership_type": "Community Member",
"valid_period": "01/06/2023 - 01/06/2024",
"language": "in azerbaijani language",
"director": "Society Ambasador Kenan Rahimov",
"teacher": "",
"source_url": "https://www.intpas.com/13iu21e3az0015"
},
{
"id": "13iu21e3az0016",
"display_id": "C032513516",
"full_name": "Fatima Suleymanzade",
"first_name": "Fatima",
"last_name": "Suleymanzade",
"email": "",
"program": "Clinical Psychotherapy course",
"module": "",
"hours": 0,
"courses_count": 1,
"courses_raw": "Clinical Psychotherapy course",
"issue_date": "2023-06-01",
"issued_by": "IPAS / IPI",
"status": "valid",
"membership_type": "Community Member",
"valid_period": "01/06/2023 - 01/06/2024",
"language": "in azerbaijani language",
"director": "Society Ambasador Kenan Rahimov",
"teacher": "",
"source_url": "https://www.intpas.com/13iu21e3az0016"
},
{
"id": "13iu21e3az0017",
"display_id": "C032513517",
"full_name": "Kenan Farhadov",
"first_name": "Kenan",
"last_name": "Farhadov",
"email": "",
"program": "Clinical Psychotherapy course",
"module": "",
"hours": 0,
"courses_count": 1,
"courses_raw": "Clinical Psychotherapy course",
"issue_date": "2023-06-01",
"issued_by": "IPAS / IPI",
"status": "valid",
"membership_type": "Community Member",
"valid_period": "01/06/2023 - 01/06/2024",
"language": "in azerbaijani language",
"director": "Society Ambasador Kenan Rahimov",
"teacher": "",
"source_url": "https://www.intpas.com/13iu21e3az0017"
},
{
"id": "13iu21e3az0018",
"display_id": "C032513518",
"full_name": "Leman Ibrahimli",
"first_name": "Leman",
"last_name": "Ibrahimli",
"email": "",
"program": "Clinical Psychotherapy course",
"module": "",
"hours": 0,
"courses_count": 1,
"courses_raw": "Clinical Psychotherapy course",
"issue_date": "2023-06-01",
"issued_by": "IPAS / IPI",
"status": "valid",
"membership_type": "Community Member",
"valid_period": "01/06/2023 - 01/06/2024",
"language": "in azerbaijani language",
"director": "Society Ambasador Kenan Rahimov",
"teacher": "",
"source_url": "https://www.intpas.com/13iu21e3az0018"
},
{
"id": "13iu21e3az0019",
"display_id": "C032513519",
"full_name": "Leyla Ahmadova",
"first_name": "Leyla",
"last_name": "Ahmadova",
"email": "",
"program": "Clinical Psychotherapy course",
"module": "",
"hours": 0,
"courses_count": 1,
"courses_raw": "Clinical Psychotherapy course",
"issue_date": "2023-06-01",
"issued_by": "IPAS / IPI",
"status": "valid",
"membership_type": "Community Member",
"valid_period": "01/06/2023 - 01/06/2024",
"language": "in azerbaijani language",
"director": "Society Ambasador Kenan Rahimov",
"teacher": "",
"source_url": "https://www.intpas.com/13iu21e3az0019"
},
{
"id": "13iu21e3az0020",
"display_id": "C032513520",
"full_name": "Metanet Najafova",
"first_name": "Metanet",
"last_name": "Najafova",
"email": "",
"program": "Clinical Psychotherapy course",
"module": "",
"hours": 0,
"courses_count": 1,
"courses_raw": "Clinical Psychotherapy course",
"issue_date": "2023-06-01",
"issued_by": "IPAS / IPI",
"status": "valid",
"membership_type": "Community Member",
"valid_period": "01/06/2023 - 01/06/2024",
"language": "in azerbaijani language",
"director": "Society Ambasador Kenan Rahimov",
"teacher": "",
"source_url": "https://www.intpas.com/13iu21e3az0020"
},
{
"id": "13iu21e3az0021",
"display_id": "C032513521",
"full_name": "Nurida Dashdemirli",
"first_name": "Nurida",
"last_name": "Dashdemirli",
"email": "",
"program": "Clinical Psychotherapy course",
"module": "",
"hours": 0,
"courses_count": 1,
"courses_raw": "Clinical Psychotherapy course",
"issue_date": "2023-06-01",
"issued_by": "IPAS / IPI",
"status": "valid",
"membership_type": "Community Member",
"valid_period": "01/06/2023 - 01/06/2024",
"language": "in azerbaijani language",
"director": "Society Ambasador Kenan Rahimov",
"teacher": "",
"source_url": "https://www.intpas.com/13iu21e3az0021"
},
{
"id": "13iu21e3az0022",
"display_id": "C032513522",
"full_name": "Pervana Kerimova",
"first_name": "Pervana",
"last_name": "Kerimova",
"email": "",
"program": "Clinical Psychotherapy course",
"module": "",
"hours": 0,
"courses_count": 1,
"courses_raw": "Clinical Psychotherapy course",
"issue_date": "2023-06-01",
"issued_by": "IPAS / IPI",
"status": "valid",
"membership_type": "Community Member",
"valid_period": "01/06/2023 - 01/06/2024",
"language": "in azerbaijani language",
"director": "Society Ambasador Kenan Rahimov",
"teacher": "",
"source_url": "https://www.intpas.com/13iu21e3az0022"
},
{
"id": "13iu21e3az0023",
"display_id": "C032513523",
"full_name": "Rena Mirzoyeva",
"first_name": "Rena",
"last_name": "Mirzoyeva",
"email": "",
"program": "Clinical Psychotherapy course",
"module": "",
"hours": 0,
"courses_count": 1,
"courses_raw": "Clinical Psychotherapy course",
"issue_date": "2023-06-01",
"issued_by": "IPAS / IPI",
"status": "valid",
"membership_type": "Community Member",
"valid_period": "01/06/2023 - 01/06/2024",
"language": "in azerbaijani language",
"director": "Society Ambasador Kenan Rahimov",
"teacher": "",
"source_url": "https://www.intpas.com/13iu21e3az0023"
},
{
"id": "13iu21e3az0024",
"display_id": "C032513524",
"full_name": "Regsana Huseynova",
"first_name": "Regsana",
"last_name": "Huseynova",
"email": "",
"program": "Clinical Psychotherapy course",
"module": "",
"hours": 0,
"courses_count": 1,
"courses_raw": "Clinical Psychotherapy course",
"issue_date": "2023-06-01",
"issued_by": "IPAS / IPI",
"status": "valid",
"membership_type": "Community Member",
"valid_period": "01/06/2023 - 01/06/2024",
"language": "in azerbaijani language",
"director": "Society Ambasador Kenan Rahimov",
"teacher": "",
"source_url": "https://www.intpas.com/13iu21e3az0024"
},
{
"id": "13iu21e3az0025",
"display_id": "C032513525",
"full_name": "Samira Gahramanova",
"first_name": "Samira",
"last_name": "Gahramanova",
"email": "",
"program": "Clinical Psychotherapy course",
"module": "",
"hours": 0,
"courses_count": 1,
"courses_raw": "Clinical Psychotherapy course",
"issue_date": "2023-06-01",
"issued_by": "IPAS / IPI",
"status": "valid",
"membership_type": "Community Member",
"valid_period": "01/06/2023 - 01/06/2024",
"language": "in azerbaijani language",
"director": "Society Ambasador Kenan Rahimov",
"teacher": "",
"source_url": "https://www.intpas.com/13iu21e3az0025"
},
{
"id": "13iu21e3az0026",
"display_id": "C032513526",
"full_name": "Tarana Ismayilova",
"first_name": "Tarana",
"last_name": "Ismayilova",
"email": "",
"program": "Clinical Psychotherapy course",
"module": "",
"hours": 0,
"courses_count": 1,
"courses_raw": "Clinical Psychotherapy course",
"issue_date": "2023-06-01",
"issued_by": "IPAS / IPI",
"status": "valid",
"membership_type": "Community Member",
"valid_period": "01/06/2023 - 01/06/2024",
"language": "in azerbaijani language",
"director": "Society Ambasador Kenan Rahimov",
"teacher": "",
"source_url": "https://www.intpas.com/13iu21e3az0026"
},
{
"id": "13iu21e3az0027",
"display_id": "C032513527",
"full_name": "Vusala Alizade",
"first_name": "Vusala",
"last_name": "Alizade",
"email": "",
"program": "Clinical Psychotherapy course",
"module": "",
"hours": 0,
"courses_count": 1,
"courses_raw": "Clinical Psychotherapy course",
"issue_date": "2023-06-01",
"issued_by": "IPAS / IPI",
"status": "valid",
"membership_type": "Community Member",
"valid_period": "01/06/2023 - 01/06/2024",
"language": "in azerbaijani language",
"director": "Society Ambasador Kenan Rahimov",
"teacher": "",
"source_url": "https://www.intpas.com/13iu21e3az0027"
},
{
"id": "13iu21e3az0028",
"display_id": "C032513528",
"full_name": "Vusala Abdullayeva",
"first_name": "Vusala",
"last_name": "Abdullayeva",
"email": "",
"program": "Clinical Psychotherapy course",
"module": "",
"hours": 0,
"courses_count": 1,
"courses_raw": "Clinical Psychotherapy course",
"issue_date": "2023-06-01",
"issued_by": "IPAS / IPI",
"status": "valid",
"membership_type": "Community Member",
"valid_period": "01/06/2023 - 01/06/2024",
"language": "in azerbaijani language",
"director": "Society Ambasador Kenan Rahimov",
"teacher": "",
"source_url": "https://www.intpas.com/13iu21e3az0028"
},
{
"id": "13iu21e3az0029",
"display_id": "C032513529",
"full_name": "Chaman Abdullayeva",
"first_name": "Chaman",
"last_name": "Abdullayeva",
"email": "",
"program": "Clinical Psychotherapy course",
"module": "",
"hours": 0,
"courses_count": 1,
"courses_raw": "Clinical Psychotherapy course",
"issue_date": "2023-06-01",
"issued_by": "IPAS / IPI",
"status": "valid",
"membership_type": "Community Member",
"valid_period": "01/06/2023 - 01/06/2024",
"language": "in azerbaijani language",
"director": "Society Ambasador Kenan Rahimov",
"teacher": "",
"source_url": "https://www.intpas.com/13iu21e3az0029"
},
{
"id": "13iu21e3az0030",
"display_id": "C032513530",
"full_name": "Khayala Khasmemmedli",
"first_name": "Khayala",
"last_name": "Khasmemmedli",
"email": "",
"program": "Clinical Psychotherapy course",
"module": "",
"hours": 0,
"courses_count": 1,
"courses_raw": "Clinical Psychotherapy course",
"issue_date": "2023-06-01",
"issued_by": "IPAS / IPI",
"status": "valid",
"membership_type": "Community Member",
"valid_period": "01/06/2023 - 01/06/2024",
"language": "in azerbaijani language",
"director": "Society Ambasador Kenan Rahimov",
"teacher": "",
"source_url": "https://www.intpas.com/13iu21e3az0030"
},
{
"id": "13iu21e3az0031",
"display_id": "C032513531",
"full_name": "Zumrud Behbudova",
"first_name": "Zumrud",
"last_name": "Behbudova",
"email": "",
"program": "Clinical Psychotherapy course",
"module": "",
"hours": 0,
"courses_count": 1,
"courses_raw": "Clinical Psychotherapy course",
"issue_date": "2023-06-01",
"issued_by": "IPAS / IPI",
"status": "valid",
"membership_type": "Community Member",
"valid_period": "01/06/2023 - 01/06/2024",
"language": "in azerbaijani language",
"director": "Society Ambasador Kenan Rahimov",
"teacher": "",
"source_url": "https://www.intpas.com/13iu21e3az0031"
},
{
"id": "13iu21e3az0032",
"display_id": "C032513532",
"full_name": "Ulkar Arabkhanova",
"first_name": "Ulkar",
"last_name": "Arabkhanova",
"email": "",
"program": "Clinical Psychotherapy course",
"module": "",
"hours": 0,
"courses_count": 1,
"courses_raw": "Clinical Psychotherapy course",
"issue_date": "2023-06-01",
"issued_by": "IPAS / IPI",
"status": "valid",
"membership_type": "Community Member",
"valid_period": "01/06/2023 - 01/06/2024",
"language": "in azerbaijani language",
"director": "Society Ambasador Kenan Rahimov",
"teacher": "",
"source_url": "https://www.intpas.com/13iu21e3az0032"
},
{
"id": "13iu21e3az0033",
"display_id": "C032513533",
"full_name": "Parvana Mammadova",
"first_name": "Parvana",
"last_name": "Mammadova",
"email": "",
"program": "Clinical Psychotherapy course",
"module": "",
"hours": 0,
"courses_count": 1,
"courses_raw": "Clinical Psychotherapy course",
"issue_date": "2023-10-05",
"issued_by": "IPAS / IPI",
"status": "valid",
"membership_type": "Community Member",
"valid_period": "05/10/2023 - 05/10/2024",
"language": "in azerbaijani language",
"director": "Society Ambasador Kenan Rahimov",
"teacher": "",
"source_url": "https://www.intpas.com/13iu21e3az0033"
},
{
"id": "13iu21e3az0034",
"display_id": "C032513534",
"full_name": "Tamilla Suleymanova",
"first_name": "Tamilla",
"last_name": "Suleymanova",
"email": "",
"program": "Clinical Psychotherapy course",
"module": "",
"hours": 0,
"courses_count": 1,
"courses_raw": "Clinical Psychotherapy course",
"issue_date": "2023-10-05",
"issued_by": "IPAS / IPI",
"status": "valid",
"membership_type": "Community Member",
"valid_period": "05/10/2023 - 05/10/2024",
"language": "in azerbaijani language",
"director": "Society Ambasador Kenan Rahimov",
"teacher": "",
"source_url": "https://www.intpas.com/13iu21e3az0034"
},
{
"id": "13iu21e3az0035",
"display_id": "C032513535",
"full_name": "Ruhangiz Akberova",
"first_name": "Ruhangiz",
"last_name": "Akberova",
"email": "",
"program": "Basic Psychotherapy course",
"module": "",
"hours": 0,
"courses_count": 1,
"courses_raw": "Basic Psychotherapy course",
"issue_date": "2024-01-03",
"issued_by": "IPAS / IPI",
"status": "valid",
"membership_type": "Community Member",
"valid_period": "03/01/2024 - 05/01/2025",
"language": "in azerbaijani language",
"director": "Society Ambasador Kenan Rahimov",
"teacher": "",
"source_url": "https://www.intpas.com/13iu21e3az0035"
},
{
"id": "13iu21e3az0036",
"display_id": "C032513536",
"full_name": "Konul Babashzade",
"first_name": "Konul",
"last_name": "Babashzade",
"email": "",
"program": "Basic Psychotherapy course",
"module": "",
"hours": 0,
"courses_count": 1,
"courses_raw": "Basic Psychotherapy course",
"issue_date": "2024-01-03",
"issued_by": "IPAS / IPI",
"status": "valid",
"membership_type": "Community Member",
"valid_period": "03/01/2024 - 05/01/2025",
"language": "in azerbaijani language",
"director": "Society Ambasador Kenan Rahimov",
"teacher": "",
"source_url": "https://www.intpas.com/13iu21e3az0036"
},
{
"id": "13iu21e3az0037",
"display_id": "C032513537",
"full_name": "Aysel Bashirova",
"first_name": "Aysel",
"last_name": "Bashirova",
"email": "",
"program": "Couples Counselling",
"module": "",
"hours": 0,
"courses_count": 1,
"courses_raw": "Couples Counselling",
"issue_date": "2024-01-03",
"issued_by": "IPAS / IPI",
"status": "valid",
"membership_type": "Community Member",
"valid_period": "03/01/2024 - 05/01/2025",
"language": "",
"director": "",
"teacher": "Society Ambasador Kenan Rahimov",
"source_url": "https://www.intpas.com/13iu21e3az0037"
},
{
"id": "13iu21e3az0038",
"display_id": "C032513538",
"full_name": "Ilaha Kadirova",
"first_name": "Ilaha",
"last_name": "Kadirova",
"email": "",
"program": "Couples Counselling",
"module": "",
"hours": 0,
"courses_count": 1,
"courses_raw": "Couples Counselling",
"issue_date": "2024-01-03",
"issued_by": "IPAS / IPI",
"status": "valid",
"membership_type": "Community Member",
"valid_period": "03/01/2024 - 05/01/2025",
"language": "",
"director": "",
"teacher": "Society Ambasador Kenan Rahimov",
"source_url": "https://www.intpas.com/13iu21e3az0038"
},
{
"id": "13iu21e3az0039",
"display_id": "C032513539",
"full_name": "Irada Babayeva",
"first_name": "Irada",
"last_name": "Babayeva",
"email": "",
"program": "Couples Counselling",
"module": "",
"hours": 0,
"courses_count": 1,
"courses_raw": "Couples Counselling",
"issue_date": "2024-01-03",
"issued_by": "IPAS / IPI",
"status": "valid",
"membership_type": "Community Member",
"valid_period": "03/01/2024 - 05/01/2025",
"language": "",
"director": "",
"teacher": "Society Ambasador Kenan Rahimov",
"source_url": "https://www.intpas.com/13iu21e3az0039"
},
{
"id": "13iu21e3az0040",
"display_id": "C032513540",
"full_name": "Sevda Karimzade",
"first_name": "Sevda",
"last_name": "Karimzade",
"email": "",
"program": "Couples Counselling",
"module": "",
"hours": 0,
"courses_count": 1,
"courses_raw": "Couples Counselling",
"issue_date": "2024-01-03",
"issued_by": "IPAS / IPI",
"status": "valid",
"membership_type": "Community Member",
"valid_period": "03/01/2024 - 05/01/2025",
"language": "",
"director": "",
"teacher": "Society Ambasador Kenan Rahimov",
"source_url": "https://www.intpas.com/13iu21e3az0040"
},
{
"id": "13iu21e3az0041",
"display_id": "C032513541",
"full_name": "Zarintaj Jabizade",
"first_name": "Zarintaj",
"last_name": "Jabizade",
"email": "",
"program": "Couples Counselling",
"module": "",
"hours": 0,
"courses_count": 1,
"courses_raw": "Couples Counselling",
"issue_date": "2024-01-03",
"issued_by": "IPAS / IPI",
"status": "valid",
"membership_type": "Community Member",
"valid_period": "03/01/2024 - 05/01/2025",
"language": "",
"director": "",
"teacher": "Society Ambasador Kenan Rahimov",
"source_url": "https://www.intpas.com/13iu21e3az0041"
},
{
"id": "13iu21e3az0042",
"display_id": "C032513542",
"full_name": "Zulfiyya Najafova",
"first_name": "Zulfiyya",
"last_name": "Najafova",
"email": "",
"program": "Couples Counselling",
"module": "",
"hours": 0,
"courses_count": 1,
"courses_raw": "Couples Counselling",
"issue_date": "2024-01-03",
"issued_by": "IPAS / IPI",
"status": "valid",
"membership_type": "Community Member",
"valid_period": "03/01/2024 - 05/01/2025",
"language": "",
"director": "",
"teacher": "Society Ambasador Kenan Rahimov",
"source_url": "https://www.intpas.com/13iu21e3az0042"
},
{
"id": "13iu21e3az0043",
"display_id": "C032513543",
"full_name": "Sariyya Farajova",
"first_name": "Sariyya",
"last_name": "Farajova",
"email": "",
"program": "Couples Counselling",
"module": "",
"hours": 0,
"courses_count": 1,
"courses_raw": "Couples Counselling",
"issue_date": "2024-01-03",
"issued_by": "IPAS / IPI",
"status": "valid",
"membership_type": "Community Member",
"valid_period": "03/01/2024 - 05/01/2025",
"language": "",
"director": "",
"teacher": "Society Ambasador Kenan Rahimov",
"source_url": "https://www.intpas.com/13iu21e3az0043"
}
];
